[repository.api_bindium]
path="./"
default_branch="master"

    [repository.api_bindium.release]
    git_cliff = true

    [repository.api_bindium.rust]
    fmt = true
    clippy_hack = true
    sqlx = false

    [repository.api_bindium.rust.ci]
    fmt = true
    clippy = false
    test = true
    nextest = false
    msrv = true
    machete = true
    #semver = true <- Need nightly as well but break CI...