[package]
name = "api_maker"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]

# Fetching
ureq = "3.1.4"
governor = {version = "0.10.2", optional = true}

# Async
async-generic = "1.1.2"
blocking = {version = "1.6.2", optional = true}
async-io = {version = "2.6.0", optional = true}

# Debuging
tracing = {version = "0.1.41", optional = true}
hotpath = { version = "0.7.3", optional = true }

# Others
bon = "3.8.1"
serde = "1.0.228"
serde_json = "1.0.145"
snafu = "0.8.9"


[features]
default = []

# Async
sync = []
async = ["dep:blocking", "dep:async-io"]

# Fetching
native_tls = ["ureq/native-tls"]
rate_limit = ["dep:governor", "async"]

# Debugging
backtrace = []
tracing = ["dep:tracing"]
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-off = ["hotpath/hotpath-off"]
